include: package:very_good_analysis/analysis_options.yaml

analyzer:
  errors:
    directives_ordering: ignore
    lines_longer_than_80_chars: ignore
    missing_whitespace_between_adjacent_strings: ignore
    parameter_assignments: ignore
    prefer_constructors_over_static_methods: ignore
  exclude:
    - lib/**.graphql.dart
    - lib/**.g.dart
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    always_use_package_imports: false
    avoid_redundant_argument_values: false
    library_prefixes: false
    no_runtimeType_toString: false
    one_member_abstracts: false
    prefer_single_quotes: false
    public_member_api_docs: false
    unnecessary_brace_in_string_interps: false
