targets:
  $default:
    builders:
      slang_build_runner:
        options:
          base_locale: en
          fallback_strategy: base_locale
          input_directory: assets/i18n
          input_file_pattern: .i18n.yaml
          locale_handling: true
          flutter_integration: true
          translate_var: t
          translation_class_visibility: private
          string_interpolation: dart