name: vdc
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  dart_mappable: ^4.2.2
  file_picker: ^8.1.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  hugeicons: ^0.0.7
  intl: any
  path: ^1.9.0
  shared_preferences: ^2.3.2
  slang: ^3.31.2
  slang_flutter: ^3.31.0
  system_theme: ^3.1.0
  window_manager: ^0.4.2

dev_dependencies:
  build_runner: ^2.4.12
  dart_mappable_builder: ^4.2.3
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  slang_build_runner: ^3.31.0
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
